### ISSUE TITLE
brackets differ in 3 examples in this lesson

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/partial-locals-reading#12]
The less shows 'conflicting' syntax, or perhaps both work?, when depicting brackets in the hash passed to a partial.

This reference seems to agree with examples 1 and 3: 
http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials
Example:  <%= render partial: "form", locals: {zone: @zone} %>

Lesson example 1:
<%= render partial: "authors/author", locals: {post_author: @author} %>

Lesson example 2:
<%= render {partial: "authors/author", locals: {post_author: @author}} %>
### are these {} brackets a mistake? (not consistent with the examples 1 and 3 above and below)

Lesson example 3: 
Information About the Post
<%= render partial: "authors/author", locals: {post_author: @post.author} %>
<%= @post.title %>
<%= @post.content %>

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
