### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by cdudhat** [learn-co-curriculum/partial-locals-reading#13]
Does not provide any information regarding what happens to the `app/views/authors/show.html.erb` and `app/views/authors/index.html.erb`.

These views also contain `@author` reference. Upon changing the `_author` partial to refer to `post_author`, it coincides with `post_author` usage in `app/views/posts/show.html.erb`, but what happens to the dependencies of the above two `author` views?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
