### ISSUE TITLE
Mixed local and instance variables throughout the views.

### ISSUE THREAD

**Issue by veloblank** [learn-co-curriculum/partial-locals-reading#14]
There are mixed local and Instance variables throughout the readme. Is this intentional?

**Comment by sgharms** [comment]
Hard to say, there are many ways of passing these data across.

Often we want to pass the biggest "thing" possible _from the controller_ that serves the outer-most view. From _that view_, however, we want to pass the narrowest thing that satisfies the partial.

Typically Rails pros pass 1 or two `@` variables from the controller and then pass things "contained" or "accessible" through them into partials via `locals`.
