### ISSUE TITLE
Incorrect code

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/partial-locals-reading#15]
Hi, I noticed a few inaccuracies in the code for this lab. Specifically, the post index page uses iterates through all the posts with this line `<%= @posts.each do |post| %>` - rendering the @posts array. Also, in many of the views, a local variable `author` which does not exist is used instead of the instance variable `@author`. This causes an error if you add routes and run the browser. Thanks!

**Comment by atxrenegade** [comment]
View pages do not display correctly if lab directions are followed.

**Comment by sgharms** [comment]
Fixed in d9c69d8
