### ISSUE TITLE
Was not able to open this lab with learn gem

### ISSUE THREAD

**Issue by jhharwood88** [learn-co-curriculum/partial-locals-reading#18]
I would also like to add i was unable to use the learn function on my local without going to the repo and forking/cloning directly. 

learn open partial-locals-reading-online-web-ft-031119
Looking for lesson...
/home/jon/.rvm/gems/ruby-2.3.7/gems/learn-open-1.2.28/lib/learn_open/lessons/ios_lesson.rb:6:in `detect': undefined method `any?' for false:FalseClass (NoMethodError)
	from /home/jon/.rvm/gems/ruby-2.3.7/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:20:in `block in classify'
	from /home/jon/.rvm/gems/ruby-2.3.7/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:19:in `each'
	from /home/jon/.rvm/gems/ruby-2.3.7/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:19:in `find'
	from /home/jon/.rvm/gems/ruby-2.3.7/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:19:in `classify'
	from /home/jon/.rvm/gems/ruby-2.3.7/gems/learn-open-1.2.28/lib/learn_open/opener.rb:38:in `run'
	from /home/jon/.rvm/gems/ruby-2.3.7/gems/learn-open-1.2.28/lib/learn_open/opener.rb:12:in `run'
	from /home/jon/.rvm/gems/ruby-2.3.7/gems/learn-open-1.2.28/bin/learn-open:7:in `<top (required)>'
	from /home/jon/.rvm/gems/ruby-2.3.7/bin/learn-open:23:in `load'
	from /home/jon/.rvm/gems/ruby-2.3.7/bin/learn-open:23:in `<main>'
	from /home/jon/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `eval'
	from /home/jon/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `<main>'

**Comment by sachinm78** [comment]
I had the same error in the Learn IDE.  Seems like the lab is missing.

**Comment by barbarajohnsonATX** [comment]
I'm not able to open this lesson:

```
1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons.rb:20:in `block in classify'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-open-1.2.28/lib/learn_open/lessons/ios_lesson.rb:6:in `detect': undefined method `any?' for false:FalseClass (NoMethodError)
```

**Comment by ivalentine** [comment]
Student @MNGiit is having the same issue trying to open this lab in the in-browser IDE.

**Comment by abogailo** [comment]
I am having the same issue with the same error.

**Comment by gzavaglia** [comment]
same here

**Comment by sgharms** [comment]
Very strange. Will look into it.
