### ISSUE TITLE
learn is not worked

### ISSUE THREAD

**Issue by HuydDo** [learn-co-curriculum/partial-locals-reading#21]
Hi! I run 
gem install bundler:2.0.1
and follow the instructions, but I can't run learn at all.

This can be fixed by doing the following:

Add gem 'rspec-rails', ">= 2.0.0.beta" to the gemfile
Run bundle install
Run rails generate rspec:install
Run learn test
Run learn submit

This adds spec files to the lab so that it can be properly submitted
Thanks,

I was advised to run this : "gem install learn-co" and it fixed the learn issue.

**Comment by ivalentine** [comment]
I encountered this issue with @maasa333 today. It looks like this lesson is incorrectly categorized as a lab on Learn — it should be categorized as a lesson so that tests are not required.

**Comment by Ingrid04** [comment]
Hi. I tried to do that, but it still not working. It says this: 
- You must use Bundler 2 or greater with this
lockfile.
- Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails

You can then rerun your "rails" command.
But I don't want to install the latest rails version ...
Thank you!

**Comment by kwebster2** [comment]
@sgharms FYI, looks like this is incorrectly marked as a lab - had a student with a similar error today. Thanks!
