### ISSUE TITLE
Not opening the lesson

### ISSUE THREAD

**Issue by zivolution921** [learn-co-curriculum/partial-locals-reading#6]
After forking the lesson and cloning the lesson is in my computer but it does not go through learn, getting these errors:

Looking for lesson...
Forking lesson...
Cloning lesson...
/Users/ziv/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:231:in `read': No such file or directory @ rb_sysopen - /Users/ziv/Development/code/partial-locals-reading-v-000/.learn (Errno::ENOENT)
	from /Users/ziv/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:231:in `ios_lesson?'
	from /Users/ziv/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:296:in `bundle_install'
	from /Users/ziv/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:33:in `run'
	from /Users/ziv/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/lib/learn_open/opener.rb:7:in `run'
	from /Users/ziv/.rvm/gems/ruby-2.2.3/gems/learn-open-1.1.57/bin/learn-open:7:in `<top (required)>'
	from /Users/ziv/.rvm/gems/ruby-2.2.3/bin/learn-open:23:in `load'
	from /Users/ziv/.rvm/gems/ruby-2.2.3/bin/learn-open:23:in `<main>'
	from /Users/ziv/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ziv/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
logout

[Process completed]

**Comment by AnnJohn** [comment]
hi @zivolution921 sorry for the issue that you're having. Since this might be something specific to your computer, can you use the 'Ask a Question' tool and someone will get back to you there. Thanks!

**Comment by zivolution921** [comment]
Yes no problem 

    On Thursday, May 5, 2016 5:04 PM, AnnJohn <notifications@github.com> wrote:
 

 Closed #6.—
